updateInterval: 5000
targetFile: /path/to/overviewermap/markers.json
saveOfflinePlayers: true
hideVanishedPlayers: true
hideSneakingPlayers: true
hideInvisiblePlayers: true
hideSpectators: true
sendJSONOnVanishedPlayers: false
sendJSONOnSneakingPlayers: false
sendJSONOnInvisiblePlayers: false
sendJSONOnSpectators: false
offlineFile: locations.bin