name: PlayerMarkers
version: '${minecraft.plugin.version}'
decsription: Generates Markers on an Overviewer generated map
author: 1am3r, revised by braste
website: http://braste.github.com/PlayerMarkers/
dev-url: http://dev.bukkit.org/server-mods/mapmarkers/
main: de.braste.SPfB.PlayerMarkers
